---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oura
data:
  daemon.toml: |-
    [source]
    type = "N2N"
    address = ["Tcp", "relays-new.cardano-mainnet.iohk.io:3001"]
    magic = "mainnet"
    min_depth = 6

    [source.intersect]
    type = "Origin"

    [[filters]]
    type = "Fingerprint"

    [sink]
    type = "Webhook"
    url = "http://endpoint:5000/events"

    [cursor]
    type = "File"
    path = "/var/oura/cursor-test47"

    [metrics]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: oura
spec:
  selector:
    matchLabels:
      app: oura
  serviceName: oura
  replicas: 1
  template:
    metadata:
      labels:
        app: oura
    spec:
      containers:
        - name: main
          image: ghcr.io/txpipe/oura-testdrive:47
          env:
            - name: "RUST_LOG"
              value: "warn"
          resources:
            requests:
              memory: 100Mi
              cpu: 50m
            limits:
              memory: 500Mi
              cpu: 200m
          args:
            - "daemon"
          ports:
            - name: metrics
              containerPort: 9186
          volumeMounts:
            - mountPath: /etc/oura
              name: config
            - mountPath: /var/oura
              name: var
      volumes:
        - name: config
          configMap:
            name: oura
  volumeClaimTemplates:
    - metadata:
        name: var
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
