apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: endpoint
deploy:
  kubectl:
    manifests:
      - k8s/endpoint.yaml
---
apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: oura
requires:
  - configs: [endpoint]
deploy:
  kubectl:
    manifests:
      - k8s/oura.yaml
